apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: restreamer
spec:
  selector:
    matchLabels:
      app: restreamer
  template:
    metadata:
      labels:
        app: restreamer
    spec:
      nodeSelector:
        cloud.flussonic.com/egress: "true"
      serviceAccountName: in-api-call-sa
      containers:
      - name: flussonic
        image: flussonic/flussonic:v22.10-124
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
        env:
        - name: FLUSSONIC_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: flussonic-license
              key: license_key
              optional: false
        - name: FLUSSONIC_CONFIG_EXTERNAL
          value: "http://konfig.default.svc.cluster.local/restreamer"
        - name: FLUSSONIC_SECRETS_STORAGE
          value: "k8s://test-secret"
        - name: FLUSSONIC_HTTP
          value: "80"
        - name: FLUSSONIC_EDIT_AUTH
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: edit_auth
              optional: false
        livenessProbe:
          httpGet:
            path: /flussonic/api/v3/monitoring/liveness
            port: 80
            httpHeaders:
            - name: Authorization
              value: Bearer cm9vdDpwYXNzd29yZA==
          initialDelaySeconds: 3
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /flussonic/api/v3/monitoring/readiness
            port: 80
            httpHeaders:
            - name: Authorization
              value: Bearer cm9vdDpwYXNzd29yZA==
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /flussonic/api/v3/monitoring/readiness
            port: 80
            httpHeaders:
            - name: Authorization
              value: Bearer cm9vdDpwYXNzd29yZA==
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
      - name: config-templates
        configMap:
          name: streamer-presets
          items:
          - key: listeners
            path: listeners.conf

