apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: publish
spec:
  serviceName: publish
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app: publish
  template:
    metadata:
      labels:
        app: publish
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - publish
            topologyKey: "kubernetes.io/hostname"
      serviceAccountName: in-api-call-sa
      containers:
      - name: flussonic
        image: flussonic/flussonic:v22.09-49
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        - containerPort: 1935
          name: rtmp
        env:
        - name: LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: flussonic-license
              key: license_key
              optional: false
        - name: FLUSSONIC_SECRETS_STORAGE
          value: "k8s://test-secret"
        - name: FLUSSONIC_HTTP
          value: "80"
        - name: FLUSSONIC_EDIT_AUTH
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: edit_auth
              optional: false
        volumeMounts:
        - name: config-templates
          mountPath: /etc/flussonic/flussonic.conf.d
        livenessProbe:
          httpGet:
            path: /flussonic/api/v3/monitoring/liveness
            port: 80
            httpHeaders:
            - name: Authorization
              value: Bearer cm9vdDpwYXNzd29yZA==
          initialDelaySeconds: 3
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /flussonic/api/v3/monitoring/readiness
            port: 80
            httpHeaders:
            - name: Authorization
              value: Bearer cm9vdDpwYXNzd29yZA==
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /flussonic/api/v3/monitoring/readiness
            port: 80
            httpHeaders:
            - name: Authorization
              value: Bearer cm9vdDpwYXNzd29yZA==
          initialDelaySeconds: 3
          periodSeconds: 3

      volumes:
      - name: config-templates
        configMap:
          name: streamer-presets
          items:
          - key: rtmp
            path: rtmp.conf
          - key: publish
            path: publish.conf
          - key: cluster_key
            path: cluster_key.conf
---
apiVersion: v1
kind: Service
metadata:
  name: ingress
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "ingress-publish-lb-02"
spec:
  type: LoadBalancer
  selector:
    app: publish
  ports:
  - port: 1935
    name: rtmp
    targetPort: rtmp
  - port: 80
    name: http
    targetPort: http
