apiVersion: v1
kind: Service
metadata:
  name: konfig
  labels:
    name: konfig
spec:
  ports:
  - port: 80
    targetPort: 3000
    name: konfig
  selector:
    app: konfig
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: konfig
spec:
  serviceName: konfig
  replicas: 1
  selector:
    matchLabels:
      app: konfig
  template:
    metadata:
      labels:
        app: konfig
    spec:
      containers:
      - name: konfig
        image: flussonic/tutorial-03-dynamic-konfig:1.1
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://flus:sonic@mongo.default.svc.cluster.local:27017/flussonic?authSource=admin"

