apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transcoder
spec:
  serviceName: transcoder
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app: transcoder
  template:
    metadata:
      labels:
        app: transcoder
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - transcoder
            topologyKey: "kubernetes.io/hostname"
      serviceAccountName: in-api-call-sa
      containers:
      - name: flussonic
        image: flussonic/flussonic:v22.09-49
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        env:
        - name: LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: flussonic-license
              key: license_key
              optional: false
        - name: FLUSSONIC_SECRETS_STORAGE
          value: "k8s://test-secret"
        - name: FLUSSONIC_HTTP
          value: "80"
        - name: FLUSSONIC_EDIT_AUTH
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: edit_auth
              optional: false
        volumeMounts:
        - name: config-templates
          mountPath: /etc/flussonic/flussonic.conf.d
        livenessProbe:
          httpGet:
            path: /flussonic/api/v3/monitoring/liveness
            port: 80
            httpHeaders:
            - name: Authorization
              value: Bearer cm9vdDpwYXNzd29yZA==
          initialDelaySeconds: 3
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /flussonic/api/v3/monitoring/readiness
            port: 80
            httpHeaders:
            - name: Authorization
              value: Bearer cm9vdDpwYXNzd29yZA==
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /flussonic/api/v3/monitoring/readiness
            port: 80
            httpHeaders:
            - name: Authorization
              value: Bearer cm9vdDpwYXNzd29yZA==
          initialDelaySeconds: 3
          periodSeconds: 3

      volumes:
      - name: config-templates
        configMap:
          name: streamer-presets
          items:
          - key: transcoder
            path: transcoder.conf
          - key: cluster_key
            path: cluster_key.conf
---
apiVersion: v1
kind: Service
metadata:
  name: transcoder
  labels:
    app: transcoder
spec:
  ports:
  - port: 80
    name: transcoder
  clusterIP: None
  selector:
    app: transcoder

