apiVersion: v1
kind: ServiceAccount
metadata:
  name: in-api-call-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: in-api-call-role
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: in-api-call-rb
subjects:
  - kind: ServiceAccount
    name: in-api-call-sa
roleRef:
  kind: Role
  name: in-api-call-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: streamer-presets
data:
  listeners: |
    http 80 {
      api false;
    }
    http 81;
  rtmp: |
    rtmp 1935;
  publish: |
    template pub {
      prefix pub;
      url publish://;
      push m4s://transcoder.default.svc.cluster.local/%s;
    }
  transcoder: |
    template pub {
      prefix pub;
      url publish://;
      #transcoder vb=1024k size=-1x360 preset=veryfast vb=700k size=-1x240 preset=veryfast ab=copy external=false;
    }
  restream: |
    source transcoder-0.transcoder.default.svc.cluster.local {
      only;
    }
    source transcoder-1.transcoder.default.svc.cluster.local {
      only;
    }
  cluster_key: |
    cluster_key mykey0;
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
# root:password
  edit_auth: cm9vdDpwYXNzd29yZA==
