apiVersion: v1
kind: ServiceAccount
metadata:
  name: in-api-call-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: in-api-call-role
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: in-api-call-rb
subjects:
  - kind: ServiceAccount
    name: in-api-call-sa
roleRef:
  kind: Role
  name: in-api-call-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
# root:password
  edit_auth: cm9vdDpwYXNzd29yZA==
