apiVersion: v1
kind: Service
metadata:
  name: central
  labels:
    name: central
spec:
  ports:
  - port: 80
    targetPort: 9000
    name: central
  selector:
    app: central
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: central
spec:
  serviceName: central
  replicas: 1
  selector:
    matchLabels:
      app: central
  template:
    metadata:
      labels:
        app: central
    spec:
      serviceAccountName: in-api-call-sa
      nodeSelector:
        watcher.flussonic.com/manage: "true"
      containers:
      - name: central
        image: flussonic/central:v23.08-35-g26050d8
        ports:
        - containerPort: 9000
          hostPort: 9000
        env:
        - name: DATABASE_URL
          value: postgres://test:test@postgres.default.svc.cluster.local:5432/test_c?search_path=central
        - name: HTTP_PORT
          value: "9000"
        - name: API_KEY
          value: apikey0
        - name: EDIT_AUTH
          value: "admin pass"
        - name: API_URL
          value: "http://central.default.svc.cluster.local"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: central-streamers-provisioner
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: in-api-call-sa
          containers:
          - name: central-provisioner
            image: flussonic/central:v23.08-35-g26050d8
            imagePullPolicy: IfNotPresent
            command:
            - /opt/central/bin/run.sh
            - -p
            env:
            - name: CLUSTER_KEY
              value: FxNtj8tU0olsD1
            - name: API_KEY
              value: apikey0
          restartPolicy: OnFailure
